// App_UI/src/app/login/login.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Users } from '../shared/users';
import { RESTAPIService } from '../shared/rest-api-service.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {

  @Input() title = 'Assessment Management | Login';

  @Output() errAlert = new EventEmitter<any>();

  userDetails: Users;
  userid: number;
  password: string;
  level: string;
   constructor(
       public restApi: RESTAPIService
   ) { }

  userValidate(): void {
    const errDetails = {eUserId: '', ePass: '', eLevel: ''};
    if (this.userid == null) {
        errDetails.eUserId = 'User ID should not be empty';
    } else if (this.password === '') {
        errDetails.ePass = 'Password should not be empty';
    } else if (this.level === 'Select a Level') {
        errDetails.eLevel = 'Select the access level';
    }
    this.errAlert.emit(errDetails);
    if (errDetails.eUserId === '' && errDetails.ePass === '' && errDetails.eLevel === '') {
        this.userDetails = {userId: this.userid, password: this.password, userAccess: this.level};
        this.restApi.loginFunc(this.userDetails).subscribe((data: {}) => {
            // redirect to register or admin page based on the response from server
        });
    }
  }

}

<form class="form-horizontal">
    <div class="form-group">
        <label>User ID</label> <input type="text" [(ngModel)]="userid" class="form-control" placeholder="User ID" required>
    </div>
    <div class="form-group">
        <label>Password</label> <input type="password" [(ngModel)]="password" class="form-control" placeholder="Password" required>
    </div>
    <div>
        <label>User Level</label> <select [(ngModel)]="level">
            <option disabled selected>Select a Level</option>
            <option>Employee</option>
            <option>Admin</option>
        </select>
    </div>
    <button type="submit" class="btn btn-black" (click)="userValidate()">Login</button>
</form>

// ReactUI/src/components/login/Login.jsx
import React, { Component } from 'react';
import { Button, Row, Col, Form, InputGroup } from 'react-bootstrap';
import './login.css';
import { Formik } from 'formik';

export class Login extends Component {
    render() {
        return (
            <Row>
                <Col xs={4} className="sidenav">
                    <h2>
                        Assessment Management<br /> Login Page
                    </h2>
                    <p>Login and Register for Assessment.</p>
                </Col>
                <Col xs={8} className="login-form">
                    <Formik initialValues={{ userId: "", password: "", level: "0" }}
                        onSubmit={(values, { setSubmitting, resetForm }) => {
                            setSubmitting(true);
                            setTimeout(() => {
                                alert(JSON.stringify(values, null, 2));
                                resetForm();
                                setSubmitting(false);
                            }, 2000);
                        }}
                    >
                        {({ values, errors, touched, handleChange, handleBlur, handleSubmit, isSubmitting }) => (
                            <Form className="form-horizontal" onSubmit={handleSubmit}>
                                <InputGroup className="mb-3">
                                    <InputGroup.Text>User ID</InputGroup.Text>
                                    <Form.Control
                                        id="userId"
                                        name="userId"
                                        type="text"
                                        placeholder="User ID"
                                        onChange={handleChange}
                                        onBlur={handleBlur}
                                        value={values.userId}
                                        required
                                    />
                                </InputGroup>
                                <InputGroup className="mb-3">
                                    <InputGroup.Text>Password</InputGroup.Text>
                                    <Form.Control
                                        id="password"
                                        name="password"
                                        type="password"
                                        placeholder="Password"
                                        onChange={handleChange}
                                        onBlur={handleBlur}
                                        value={values.password}
                                        required
                                    />
                                </InputGroup>
                                <InputGroup className="mb-3">
                                    <InputGroup.Text>User Level</InputGroup.Text>
                                    <Form.Select name="level" id="level"
                                        onChange={handleChange}
                                        onBlur={handleBlur}
                                        value={values.level}>
                                        <option value="0" disabled>
                                            Select a Level
                                        </option>
                                        <option value="1">Employee</option>
                                        <option value="2">Admin</option>
                                    </Form.Select>
                                </InputGroup>
                                <Button type="submit" variant="dark" disabled={isSubmitting} onClick={!isSubmitting}>
                                    {isSubmitting ? 'Logging In...' : 'Login'}
                                </Button>
                            </Form>)}
                    </Formik>
                    <div className="alert mt-3" role="alert">
                        <strong>{/*{ errAlert.eUserId }*/}</strong>
                        <strong>{/*{ errAlert.ePass }*/}</strong>
                        <strong>{/*{ errAlert.eLevel }*/}</strong>
                    </div>
                </Col>
            </Row>
        );
    }
}

export default Login;
